export const API_URLS = {
  AUTH: {
    LOGIN: "/auth/login",
    REGISTER: "/auth/register",
    ONBOARDING: "/auth/onboarding",
    RECOVER: "/auth/recover",
  },
  USERS: {
    BASE: "/users",
    BY_ID: (id: number | string) => `/users/${id}`,
  },
  AWBS: {
    BASE: "/api/air-waybills",
    BY_ID: (id: number | string) => `/api/air-waybills/${id}`,
    STATUS: (id: number | string) => `/api/air-waybills/${id}/status`,
    SEARCH: "/api/air-waybills/search",
    BY_STATUS: (status: string) => `/api/air-waybills/status/${status}`,
    BY_CUSTOMER: (customerId: number | string) => `/api/air-waybills/customer/${customerId}`,
    PENDING: "/api/air-waybills/pending",
  },
  CUSTOMERS: {
    BASE: "/api/customers",
    BY_ID: (id: number | string) => `/api/customers/${id}`,
    AI_CONFIG: (id: number | string) => `/api/customers/${id}/ai-config`,
    SEARCH: "/api/customers/search",
    LIST: "/api/customers/list",
  },
  INVOICES: {
    BASE: "/api/invoices",
    BY_ID: (id: number | string) => `/api/invoices/${id}`,
    STATUS: (id: number | string) => `/api/invoices/${id}/status`,
    BY_STATUS: (status: string) => `/api/invoices/status/${status}`,
    BY_CUSTOMER: (customerId: number | string) => `/api/invoices/customer/${customerId}`,
    BY_CUSTOMER_MONTHLY: (customerId: number | string) => `/api/invoices/customer/${customerId}/monthly`,
    GENERATE_MONTHLY: "/api/invoices/generate-monthly",
    EXPORT: (id: number | string) => `/api/invoices/export/${id}`,
    EXPORT_DATERANGE: "/api/invoices/export/daterange",
  },
  REPORTS: {
    DASHBOARD: "/api/reports/dashboard",
    OPERATIONS: "/api/reports/operations",
    CUSTOMERS: "/api/reports/customers",
    INVOICING: "/api/reports/invoicing",
    COMMISSIONS: "/api/reports/commissions",
    EXPORT: (reportType: string) => `/api/reports/export/${reportType}`,
  },
} as const;
